### ISSUE TITLE
Embedded view links are redirected to blank unsaved project page

### ISSUE THREAD

**Issue by mandarsd** [plnkr/feedback#593] opened 2023-05-15 19:27 UTC
**Describe the bug**
Opening 'Embedded view' from My Plunks gallery or directly accessing the Embedded view URL redirects to blank a plunk with title 'Unsaved Project'

**To Reproduce**
1. Go to My Plunks and open the Embedded view of any project or open this example URL (https://embed.plnkr.co/plunk/bMLQL51OrR26lioc)

**Expected behavior**
Project should be visible in Embedded view

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 113.0.5672.93 (Official Build) (64-bit)

**Comment by ggoodman** [comment] 2023-05-17 14:01
Marking as duplicate of #592.

**Closed as not planned by ggoodman** 2023-05-17 14:01 UTC
Labels: bug, duplicate
