### ISSUE TITLE
This is stupid,,,  OMG SLOW AS HELL..

### ISSUE THREAD

**Issue by akshayverma172** [plnkr/feedback#159] opened 2018-07-28 18:38 UTC
Everytime i get a link of plnkr for reference it never works it opens fine and whenever it says Loading.... in the dom view and it just stays the same forever.... Please fk fix this issue

**Comment by ggoodman** [comment] 2018-08-06 12:43
Duplicate of #61. Please see the potential solution linked there.

**Closed by ggoodman** 2018-08-06 12:43 UTC
Labels: duplicate
