### ISSUE TITLE
Error saving plunk....internal error servr

### ISSUE THREAD

**Issue by msalgadou** [plnkr/feedback#540] opened 2020-10-03 04:00 UTC
![image](https://user-images.githubusercontent.com/72290087/94982786-d5896180-0513-11eb-8ee3-7277c54e622f.png)

**Comment by ggoodman** [comment] 2020-10-03 16:40
Hi @msalgadou that looks very frustrating. So sorry about that. Is the error still occurring? Is the `.csv` file there fairly large?

**Comment by msalgadou** [comment] 2020-10-04 05:45
Yes, the error still remains and I cannot record. The csv file is small with only 18 rows

**Comment by boghyon** [comment] 2020-10-10 18:00
@ggoodman Same here. I'm not able to save a plunk if a new file, of which the name hasn't existed before previously saved state, was created.

Steps to reproduce:

1. Create a new plunk: https://plnkr.co/edit/
2. Click <kbd>Save</kbd>, enter the project title, and click <kbd>Save</kbd> from the dialog. --> The green message toast notifies that the project was saved successfully.
2. In the same project, create a new file.
3. Click <kbd>Save</kbd> again. --> The project cannot be saved due to an internal error (500).

**Comment by ggoodman** [comment] 2020-10-10 19:13
So glad you added that detail. I'll take a look today

**Comment by ggoodman** [comment] 2020-10-10 19:17
I've been able to reproduce. I should be able to fix this when I have a chance to sit down for a few minutes. Thanks for your input @boghyon.

**Comment by ggoodman** [comment] 2020-10-11 00:40
This issue should now be fixed in production. LMK if you see any regressions and thanks for bringing this to my attention with all these details! 🎉

**Closed as completed** 2020-10-11 00:40 UTC
Labels: bug, needs-triage
