### ISSUE TITLE
I can't save or fork my plunks.

### ISSUE THREAD

**Issue by Laurenivy8** [plnkr/feedback#539] opened 2020-09-17 05:40 UTC
**Describe the bug**
Hello, I went to save my plunk, so that I could come back to it later but it said Error saving plunk: An internal server error occurred. Also says this when trying to fork it as well.
**To Reproduce**
1. Go to '.Save..'
2. Click on '.Save...'
3. Scroll down to 'The Bottom of page....'
4. See error Error saving plunk: An internal server error occurred. 

**Errors / logs in developer tools**
Please open developer tools and copy/paste (or take a screenshot of) information that you think would help the team diagnose and fix the issue. We're all developers here after all, so think about what *you* would want to know to fix the issue! :heart: 
![Screenshot 2020-09-17 at 1 35 02 AM](https://user-images.githubusercontent.com/70175811/93424545-3b27ed80-f886-11ea-9318-523ecc85f2b6.png)
![Screenshot 2020-09-17 at 1 34 46 AM](https://user-images.githubusercontent.com/70175811/93424583-4aa73680-f886-11ea-81d0-c16a73212b86.png) 
 
**Expected behavior**
Well, I expected it to work properly I guess.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Chrome OS
 - Browser [e.g. chrome, safari] I use chrome, I have a Chromebook
 - Version [e.g. 22] Version 85.0.4183.84 (Official Build) (64-bit)

**Additional context**
I'm not sure how to fix it, I've deleted my cookies and that didn't help.

**Comment by ggoodman** [comment] 2020-09-17 20:54
Hi @Laurenivy8 I'm able to reproduce this as it seems I can't fork it either. When I delete the empty folders, I am able to fork it: https://plnkr.co/edit/y8Rm1TNdywqCFaL1.

Looks like a bug with handling empty directories!

**Comment by ggoodman** [comment] 2020-09-17 20:55
Looks like this is a duplicate of #533. I will track the issue there.

**Closed as completed by ggoodman** 2020-09-17 20:55 UTC
Labels: bug, duplicate
